name: Prueba de Compilacion

on:
  push:
    branches: [ test-compilacion ]

jobs:
  build:
    name: Compilar para ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: SoundGraphy-Linux
            icon_param: "" # Linux no incrusta iconos en el binario
          - os: windows-latest
            artifact_name: SoundGraphy-Windows
            icon_param: "--icon=logo/logo.ico"
          - os: macos-latest
            artifact_name: SoundGraphy-Mac
            icon_param: "--icon=logo/logo.icns"

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
      shell: bash

    - name: Compilar con PyInstaller
      run: |
        pyinstaller --onefile --windowed ${{ matrix.icon_param }} --name="${{ matrix.artifact_name }}" SoundGraphy.py
      shell: bash

    - name: Guardar Ejecutable de Prueba
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/SoundGraphy-Linux
          dist/SoundGraphy-Windows.exe
          dist/SoundGraphy-Mac.app
        if-no-files-found: ignore
        include-hidden-files: true