name: Crear Release Oficial

on:
  push:
    tags:
      - 'v*' # Se activará solo cuando subas un tag que empiece con 'v' (ej. v1.0.0)

jobs:
  build:
    name: Compilar para ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: SoundGraphy-Linux
            icon_param: ""
          - os: windows-latest
            artifact_name: SoundGraphy-Windows.exe # Añadimos la extensión aquí para automatizar
            icon_param: "--icon=logo/logo.ico"
          - os: macos-latest
            artifact_name: SoundGraphy-Mac.app
            icon_param: "--icon=logo/logo.icns"

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v7

    - name: Configurar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
      shell: bash

    - name: Compilar con PyInstaller
      run: |
        # Usamos un nombre temporal plano para pyinstaller para evitar extensiones dobles
        pyinstaller --onefile --windowed ${{ matrix.icon_param }} --name="SoundGraphy" SoundGraphy.py
      shell: bash

    - name: Preparar Binarios (Evitar carpetas dist)
      run: |
        cd dist
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          # Mac necesita ir en un ZIP para no perder los permisos del .app al subirse a la Release
          zip -r ../SoundGraphy-Mac.zip SoundGraphy.app
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          mv SoundGraphy.exe ../SoundGraphy-Windows.exe
        else
          mv SoundGraphy ../SoundGraphy-Linux
        fi
      shell: bash

    - name: Subir a la Release de GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SoundGraphy-Linux
          SoundGraphy-Windows.exe
          SoundGraphy-Mac.zip
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}